# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/tmpRFzQ9o.ui'
#
# Created: Sat Oct 26 18:35:59 2013
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(582, 38)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.layout = QtGui.QHBoxLayout()
        self.layout.setSpacing(3)
        self.layout.setObjectName("layout")
        self.motor_controls = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motor_controls.sizePolicy().hasHeightForWidth())
        self.motor_controls.setSizePolicy(sizePolicy)
        self.motor_controls.setObjectName("motor_controls")
        self.gridLayout_2 = QtGui.QGridLayout(self.motor_controls)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(3)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_change_position_plus = QtGui.QPushButton(self.motor_controls)
        self.button_change_position_plus.setMinimumSize(QtCore.QSize(50, 0))
        self.button_change_position_plus.setMaximumSize(QtCore.QSize(50, 16777215))
        self.button_change_position_plus.setObjectName("button_change_position_plus")
        self.gridLayout_2.addWidget(self.button_change_position_plus, 0, 4, 1, 1)
        self.button_change_position_plus_double = QtGui.QPushButton(self.motor_controls)
        self.button_change_position_plus_double.setMinimumSize(QtCore.QSize(50, 0))
        self.button_change_position_plus_double.setMaximumSize(QtCore.QSize(50, 16777215))
        self.button_change_position_plus_double.setObjectName("button_change_position_plus_double")
        self.gridLayout_2.addWidget(self.button_change_position_plus_double, 0, 5, 1, 1)
        self.motor_position = QtGui.QDoubleSpinBox(self.motor_controls)
        self.motor_position.setMinimumSize(QtCore.QSize(150, 0))
        self.motor_position.setDecimals(5)
        self.motor_position.setMaximum(99999.0)
        self.motor_position.setSingleStep(0.1)
        self.motor_position.setObjectName("motor_position")
        self.gridLayout_2.addWidget(self.motor_position, 0, 3, 1, 1)
        self.button_change_position_minus = QtGui.QPushButton(self.motor_controls)
        self.button_change_position_minus.setMinimumSize(QtCore.QSize(50, 0))
        self.button_change_position_minus.setMaximumSize(QtCore.QSize(50, 16777215))
        self.button_change_position_minus.setObjectName("button_change_position_minus")
        self.gridLayout_2.addWidget(self.button_change_position_minus, 0, 1, 1, 1)
        self.button_change_position_minus_double = QtGui.QPushButton(self.motor_controls)
        self.button_change_position_minus_double.setMinimumSize(QtCore.QSize(50, 0))
        self.button_change_position_minus_double.setMaximumSize(QtCore.QSize(50, 16777215))
        self.button_change_position_minus_double.setObjectName("button_change_position_minus_double")
        self.gridLayout_2.addWidget(self.button_change_position_minus_double, 0, 0, 1, 1)
        self.layout.addWidget(self.motor_controls)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(70, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.layout.addWidget(self.label_2)
        self.step_size = QtGui.QDoubleSpinBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_size.sizePolicy().hasHeightForWidth())
        self.step_size.setSizePolicy(sizePolicy)
        self.step_size.setDecimals(5)
        self.step_size.setMinimum(1e-05)
        self.step_size.setSingleStep(0.1)
        self.step_size.setProperty("value", 0.1)
        self.step_size.setObjectName("step_size")
        self.layout.addWidget(self.step_size)
        self.button_stop_all_moves = QtGui.QPushButton(Form)
        self.button_stop_all_moves.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stop_all_moves.sizePolicy().hasHeightForWidth())
        self.button_stop_all_moves.setSizePolicy(sizePolicy)
        self.button_stop_all_moves.setObjectName("button_stop_all_moves")
        self.layout.addWidget(self.button_stop_all_moves)
        self.gridLayout.addLayout(self.layout, 2, 1, 1, 4)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.button_stop_all_moves, QtCore.SIGNAL("clicked()"), Form.action_stop_motor)
        QtCore.QObject.connect(self.button_change_position_plus_double, QtCore.SIGNAL("clicked()"), Form.action_change_motor_position_plus_double)
        QtCore.QObject.connect(self.button_change_position_plus, QtCore.SIGNAL("clicked()"), Form.action_change_motor_position_plus)
        QtCore.QObject.connect(self.button_change_position_minus, QtCore.SIGNAL("clicked()"), Form.action_change_motor_position_minus)
        QtCore.QObject.connect(self.button_change_position_minus_double, QtCore.SIGNAL("clicked()"), Form.action_change_motor_position_minus_double)
        QtCore.QObject.connect(self.step_size, QtCore.SIGNAL("valueChanged(double)"), Form.action_change_step)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Motor widget", None, QtGui.QApplication.UnicodeUTF8))
        self.button_change_position_plus.setText(QtGui.QApplication.translate("Form", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.button_change_position_plus_double.setText(QtGui.QApplication.translate("Form", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.button_change_position_minus.setText(QtGui.QApplication.translate("Form", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.button_change_position_minus_double.setText(QtGui.QApplication.translate("Form", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "step size:", None, QtGui.QApplication.UnicodeUTF8))
        self.button_stop_all_moves.setText(QtGui.QApplication.translate("Form", "Stop motor", None, QtGui.QApplication.UnicodeUTF8))

