# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/tmpD4BoE4.ui'
#
# Created: Tue Jan 28 18:53:41 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(805, 63)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("#value_s1,#value_s2,#value_s3,#value_s4,#value_s5 {\n"
"    font-size:20px;\n"
"    font-weight:bold;\n"
"    padding:5px;\n"
"    min-width:100px\n"
"}\n"
"#set_1,#set_2,#set_3,#set_4,#set_5 {\n"
"    background:#00ff00;\n"
"}")
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setMargin(5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.set_1 = QtGui.QWidget(Form)
        self.set_1.setObjectName("set_1")
        self.set_1_grid = QtGui.QGridLayout(self.set_1)
        self.set_1_grid.setSpacing(0)
        self.set_1_grid.setObjectName("set_1_grid")
        self.label_s1 = QtGui.QLabel(self.set_1)
        self.label_s1.setObjectName("label_s1")
        self.set_1_grid.addWidget(self.label_s1, 0, 0, 1, 1)
        self.value_s1 = QtGui.QLabel(self.set_1)
        self.value_s1.setScaledContents(True)
        self.value_s1.setAlignment(QtCore.Qt.AlignCenter)
        self.value_s1.setWordWrap(False)
        self.value_s1.setObjectName("value_s1")
        self.set_1_grid.addWidget(self.value_s1, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.set_1, 0, 2, 1, 1)
        self.set_2 = QtGui.QWidget(Form)
        self.set_2.setObjectName("set_2")
        self.set_2_g = QtGui.QGridLayout(self.set_2)
        self.set_2_g.setSpacing(0)
        self.set_2_g.setObjectName("set_2_g")
        self.label_s2 = QtGui.QLabel(self.set_2)
        self.label_s2.setObjectName("label_s2")
        self.set_2_g.addWidget(self.label_s2, 0, 0, 1, 1)
        self.value_s2 = QtGui.QLabel(self.set_2)
        self.value_s2.setScaledContents(True)
        self.value_s2.setAlignment(QtCore.Qt.AlignCenter)
        self.value_s2.setWordWrap(False)
        self.value_s2.setObjectName("value_s2")
        self.set_2_g.addWidget(self.value_s2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.set_2, 0, 3, 1, 1)
        self.set_4 = QtGui.QWidget(Form)
        self.set_4.setObjectName("set_4")
        self.set_4_g = QtGui.QGridLayout(self.set_4)
        self.set_4_g.setSpacing(0)
        self.set_4_g.setObjectName("set_4_g")
        self.label_s4 = QtGui.QLabel(self.set_4)
        self.label_s4.setObjectName("label_s4")
        self.set_4_g.addWidget(self.label_s4, 0, 0, 1, 1)
        self.value_s4 = QtGui.QLabel(self.set_4)
        self.value_s4.setScaledContents(True)
        self.value_s4.setAlignment(QtCore.Qt.AlignCenter)
        self.value_s4.setWordWrap(False)
        self.value_s4.setObjectName("value_s4")
        self.set_4_g.addWidget(self.value_s4, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.set_4, 0, 5, 1, 1)
        self.set_5 = QtGui.QWidget(Form)
        self.set_5.setObjectName("set_5")
        self.set_5_g = QtGui.QGridLayout(self.set_5)
        self.set_5_g.setSpacing(0)
        self.set_5_g.setObjectName("set_5_g")
        self.label_s5 = QtGui.QLabel(self.set_5)
        self.label_s5.setObjectName("label_s5")
        self.set_5_g.addWidget(self.label_s5, 0, 0, 1, 1)
        self.value_s5 = QtGui.QLabel(self.set_5)
        self.value_s5.setScaledContents(True)
        self.value_s5.setAlignment(QtCore.Qt.AlignCenter)
        self.value_s5.setWordWrap(False)
        self.value_s5.setObjectName("value_s5")
        self.set_5_g.addWidget(self.value_s5, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.set_5, 0, 6, 1, 1)
        self.set_3 = QtGui.QWidget(Form)
        self.set_3.setObjectName("set_3")
        self.set_3_g = QtGui.QGridLayout(self.set_3)
        self.set_3_g.setSpacing(0)
        self.set_3_g.setObjectName("set_3_g")
        self.label_s3 = QtGui.QLabel(self.set_3)
        self.label_s3.setObjectName("label_s3")
        self.set_3_g.addWidget(self.label_s3, 0, 0, 1, 1)
        self.value_s3 = QtGui.QLabel(self.set_3)
        self.value_s3.setScaledContents(True)
        self.value_s3.setAlignment(QtCore.Qt.AlignCenter)
        self.value_s3.setWordWrap(False)
        self.value_s3.setObjectName("value_s3")
        self.set_3_g.addWidget(self.value_s3, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.set_3, 0, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 9, 1, 1)
        self.status_led = QLed(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_led.sizePolicy().hasHeightForWidth())
        self.status_led.setSizePolicy(sizePolicy)
        self.status_led.setMinimumSize(QtCore.QSize(15, 15))
        self.status_led.setMaximumSize(QtCore.QSize(15, 15))
        self.status_led.setObjectName("status_led")
        self.gridLayout.addWidget(self.status_led, 0, 0, 1, 1)
        self.device_name = QtGui.QLabel(Form)
        self.device_name.setMinimumSize(QtCore.QSize(0, 0))
        self.device_name.setMaximumSize(QtCore.QSize(250, 16777215))
        self.device_name.setStyleSheet("font-weight:bold")
        self.device_name.setObjectName("device_name")
        self.gridLayout.addWidget(self.device_name, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QObject.connect(Form, QtCore.SIGNAL("created()"), self.set_1.hide)
        QtCore.QObject.connect(Form, QtCore.SIGNAL("created()"), self.set_2.hide)
        QtCore.QObject.connect(Form, QtCore.SIGNAL("created()"), self.set_3.hide)
        QtCore.QObject.connect(Form, QtCore.SIGNAL("created()"), self.set_4.hide)
        QtCore.QObject.connect(Form, QtCore.SIGNAL("created()"), self.set_5.hide)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Device value status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_s1.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.value_s1.setText(QtGui.QApplication.translate("Form", "val1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_s2.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.value_s2.setText(QtGui.QApplication.translate("Form", "val2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_s4.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.value_s4.setText(QtGui.QApplication.translate("Form", "val4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_s5.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.value_s5.setText(QtGui.QApplication.translate("Form", "val5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_s3.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.value_s3.setText(QtGui.QApplication.translate("Form", "val3", None, QtGui.QApplication.UnicodeUTF8))
        self.device_name.setText(QtGui.QApplication.translate("Form", "Device name", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import QLed
