# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_motor_widget.ui'
#
# Created: Wed Sep  3 17:30:13 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(767, 38)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.layout_horizontal = QtGui.QHBoxLayout()
        self.layout_horizontal.setSpacing(0)
        self.layout_horizontal.setObjectName("layout_horizontal")
        self.stackedWidget = QtGui.QStackedWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.ok_page = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok_page.sizePolicy().hasHeightForWidth())
        self.ok_page.setSizePolicy(sizePolicy)
        self.ok_page.setObjectName("ok_page")
        self.gridLayout_3 = QtGui.QGridLayout(self.ok_page)
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.layout = QtGui.QHBoxLayout()
        self.layout.setSpacing(3)
        self.layout.setObjectName("layout")
        self.motor_controls = QtGui.QWidget(self.ok_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motor_controls.sizePolicy().hasHeightForWidth())
        self.motor_controls.setSizePolicy(sizePolicy)
        self.motor_controls.setObjectName("motor_controls")
        self.gridLayout_2 = QtGui.QGridLayout(self.motor_controls)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(3)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_change_position_plus = QtGui.QPushButton(self.motor_controls)
        self.button_change_position_plus.setMinimumSize(QtCore.QSize(50, 0))
        self.button_change_position_plus.setMaximumSize(QtCore.QSize(50, 16777215))
        self.button_change_position_plus.setObjectName("button_change_position_plus")
        self.gridLayout_2.addWidget(self.button_change_position_plus, 0, 4, 1, 1)
        self.button_change_position_plus_double = QtGui.QPushButton(self.motor_controls)
        self.button_change_position_plus_double.setMinimumSize(QtCore.QSize(50, 0))
        self.button_change_position_plus_double.setMaximumSize(QtCore.QSize(50, 16777215))
        self.button_change_position_plus_double.setObjectName("button_change_position_plus_double")
        self.gridLayout_2.addWidget(self.button_change_position_plus_double, 0, 5, 1, 1)
        self.motor_position = QtGui.QDoubleSpinBox(self.motor_controls)
        self.motor_position.setMinimumSize(QtCore.QSize(150, 0))
        self.motor_position.setDecimals(5)
        self.motor_position.setMaximum(99999.0)
        self.motor_position.setSingleStep(0.1)
        self.motor_position.setObjectName("motor_position")
        self.gridLayout_2.addWidget(self.motor_position, 0, 3, 1, 1)
        self.button_change_position_minus = QtGui.QPushButton(self.motor_controls)
        self.button_change_position_minus.setMinimumSize(QtCore.QSize(50, 0))
        self.button_change_position_minus.setMaximumSize(QtCore.QSize(50, 16777215))
        self.button_change_position_minus.setObjectName("button_change_position_minus")
        self.gridLayout_2.addWidget(self.button_change_position_minus, 0, 1, 1, 1)
        self.button_change_position_minus_double = QtGui.QPushButton(self.motor_controls)
        self.button_change_position_minus_double.setMinimumSize(QtCore.QSize(50, 0))
        self.button_change_position_minus_double.setMaximumSize(QtCore.QSize(50, 16777215))
        self.button_change_position_minus_double.setObjectName("button_change_position_minus_double")
        self.gridLayout_2.addWidget(self.button_change_position_minus_double, 0, 0, 1, 1)
        self.layout.addWidget(self.motor_controls)
        self.label_2 = QtGui.QLabel(self.ok_page)
        self.label_2.setMinimumSize(QtCore.QSize(70, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.layout.addWidget(self.label_2)
        self.step_size = QtGui.QDoubleSpinBox(self.ok_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_size.sizePolicy().hasHeightForWidth())
        self.step_size.setSizePolicy(sizePolicy)
        self.step_size.setDecimals(5)
        self.step_size.setMinimum(1e-05)
        self.step_size.setSingleStep(0.1)
        self.step_size.setProperty("value", 0.1)
        self.step_size.setObjectName("step_size")
        self.layout.addWidget(self.step_size)
        self.pushButton_2 = QtGui.QPushButton(self.ok_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/devices/icons/macro_mode.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(19, 19))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layout.addWidget(self.pushButton_2)
        self.buttonSettings = QtGui.QPushButton(self.ok_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSettings.sizePolicy().hasHeightForWidth())
        self.buttonSettings.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/devices/icons/settings.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.buttonSettings.setIcon(icon1)
        self.buttonSettings.setIconSize(QtCore.QSize(19, 19))
        self.buttonSettings.setObjectName("buttonSettings")
        self.layout.addWidget(self.buttonSettings)
        self.button_stop_all_moves = QtGui.QPushButton(self.ok_page)
        self.button_stop_all_moves.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stop_all_moves.sizePolicy().hasHeightForWidth())
        self.button_stop_all_moves.setSizePolicy(sizePolicy)
        self.button_stop_all_moves.setStyleSheet("QPushButton{background:purple;font-weight:bold;color:#fff;}\n"
"QPushButton:disabled{ background:silver;color:grey }")
        self.button_stop_all_moves.setObjectName("button_stop_all_moves")
        self.layout.addWidget(self.button_stop_all_moves)
        self.gridLayout_3.addLayout(self.layout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.ok_page)
        self.error_tab = QtGui.QWidget()
        self.error_tab.setStyleSheet("background:red")
        self.error_tab.setObjectName("error_tab")
        self.gridLayout_4 = QtGui.QGridLayout(self.error_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtGui.QLabel(self.error_tab)
        self.label.setStyleSheet("font-weight:bold")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.error_tab)
        self.layout_horizontal.addWidget(self.stackedWidget)
        self.gridLayout.addLayout(self.layout_horizontal, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.button_change_position_plus_double, QtCore.SIGNAL("clicked()"), Form.action_change_motor_position_plus_double)
        QtCore.QObject.connect(self.button_change_position_plus, QtCore.SIGNAL("clicked()"), Form.action_change_motor_position_plus)
        QtCore.QObject.connect(self.button_change_position_minus, QtCore.SIGNAL("clicked()"), Form.action_change_motor_position_minus)
        QtCore.QObject.connect(self.button_change_position_minus_double, QtCore.SIGNAL("clicked()"), Form.action_change_motor_position_minus_double)
        QtCore.QObject.connect(self.button_stop_all_moves, QtCore.SIGNAL("clicked()"), Form.action_stop_motor)
        QtCore.QObject.connect(self.step_size, QtCore.SIGNAL("valueChanged(double)"), Form.action_change_step)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL("clicked()"), Form.action_show_sardana_macro)
        QtCore.QObject.connect(self.buttonSettings, QtCore.SIGNAL("clicked()"), Form.action_show_settings_window)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Motor widget", None, QtGui.QApplication.UnicodeUTF8))
        self.button_change_position_plus.setToolTip(QtGui.QApplication.translate("Form", "Increase position by step size", None, QtGui.QApplication.UnicodeUTF8))
        self.button_change_position_plus.setText(QtGui.QApplication.translate("Form", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.button_change_position_plus_double.setToolTip(QtGui.QApplication.translate("Form", "Increase position by (step size * 10)", None, QtGui.QApplication.UnicodeUTF8))
        self.button_change_position_plus_double.setText(QtGui.QApplication.translate("Form", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.motor_position.setToolTip(QtGui.QApplication.translate("Form", "Set motor position", None, QtGui.QApplication.UnicodeUTF8))
        self.button_change_position_minus.setToolTip(QtGui.QApplication.translate("Form", "Decrease position by step size", None, QtGui.QApplication.UnicodeUTF8))
        self.button_change_position_minus.setText(QtGui.QApplication.translate("Form", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.button_change_position_minus_double.setToolTip(QtGui.QApplication.translate("Form", "Decrease position by (step size * 10)", None, QtGui.QApplication.UnicodeUTF8))
        self.button_change_position_minus_double.setText(QtGui.QApplication.translate("Form", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "step size:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setToolTip(QtGui.QApplication.translate("Form", "Show macro window", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSettings.setToolTip(QtGui.QApplication.translate("Form", "Show attributes editor", None, QtGui.QApplication.UnicodeUTF8))
        self.button_stop_all_moves.setText(QtGui.QApplication.translate("Form", "Stop motor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "ERROR", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
