# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/tmpAKgo7w.ui'
#
# Created: Tue Jun 24 14:13:36 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(461, 255)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(461, 255))
        Form.setMaximumSize(QtCore.QSize(461, 255))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.scan_type = QtGui.QComboBox(Form)
        self.scan_type.setObjectName("scan_type")
        self.scan_type.addItem("")
        self.scan_type.addItem("")
        self.gridLayout.addWidget(self.scan_type, 0, 1, 1, 1)
        self.controls_group = QtGui.QStackedWidget(Form)
        self.controls_group.setObjectName("controls_group")
        self.rangeStopNp = QtGui.QWidget()
        self.rangeStopNp.setObjectName("rangeStopNp")
        self.formLayout = QtGui.QFormLayout(self.rangeStopNp)
        self.formLayout.setMargin(0)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_12 = QtGui.QLabel(self.rangeStopNp)
        self.label_12.setMinimumSize(QtCore.QSize(120, 0))
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.StartStopNp_start_value = QtGui.QDoubleSpinBox(self.rangeStopNp)
        self.StartStopNp_start_value.setDecimals(5)
        self.StartStopNp_start_value.setMinimum(-99999.0)
        self.StartStopNp_start_value.setMaximum(99999.0)
        self.StartStopNp_start_value.setObjectName("StartStopNp_start_value")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.StartStopNp_start_value)
        self.label_14 = QtGui.QLabel(self.rangeStopNp)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_14)
        self.StartStopNp_stop_value = QtGui.QDoubleSpinBox(self.rangeStopNp)
        self.StartStopNp_stop_value.setDecimals(5)
        self.StartStopNp_stop_value.setMinimum(-99999.0)
        self.StartStopNp_stop_value.setMaximum(99999.0)
        self.StartStopNp_stop_value.setObjectName("StartStopNp_stop_value")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.StartStopNp_stop_value)
        self.label_13 = QtGui.QLabel(self.rangeStopNp)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.StartStopNp_np_value = QtGui.QSpinBox(self.rangeStopNp)
        self.StartStopNp_np_value.setMinimum(1)
        self.StartStopNp_np_value.setMaximum(9999999)
        self.StartStopNp_np_value.setObjectName("StartStopNp_np_value")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.StartStopNp_np_value)
        self.controls_group.addWidget(self.rangeStopNp)
        self.rangeNp = QtGui.QWidget()
        self.rangeNp.setObjectName("rangeNp")
        self.formLayout_2 = QtGui.QFormLayout(self.rangeNp)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setHorizontalSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_15 = QtGui.QLabel(self.rangeNp)
        self.label_15.setMinimumSize(QtCore.QSize(120, 0))
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.RangeNp_range_value = QtGui.QDoubleSpinBox(self.rangeNp)
        self.RangeNp_range_value.setDecimals(5)
        self.RangeNp_range_value.setMinimum(-99999.0)
        self.RangeNp_range_value.setMaximum(99999.0)
        self.RangeNp_range_value.setObjectName("RangeNp_range_value")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.RangeNp_range_value)
        self.label_16 = QtGui.QLabel(self.rangeNp)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.RangeNp_np_value = QtGui.QSpinBox(self.rangeNp)
        self.RangeNp_np_value.setMinimum(1)
        self.RangeNp_np_value.setMaximum(9999999)
        self.RangeNp_np_value.setObjectName("RangeNp_np_value")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.RangeNp_np_value)
        self.controls_group.addWidget(self.rangeNp)
        self.gridLayout.addWidget(self.controls_group, 3, 0, 1, 2)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 2)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setMinimumSize(QtCore.QSize(125, 0))
        self.label_11.setStyleSheet("m")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.macro_integration_time = QtGui.QDoubleSpinBox(Form)
        self.macro_integration_time.setDecimals(5)
        self.macro_integration_time.setMinimum(0.0)
        self.macro_integration_time.setMaximum(99999.0)
        self.macro_integration_time.setObjectName("macro_integration_time")
        self.gridLayout.addWidget(self.macro_integration_time, 4, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.close_button = QtGui.QPushButton(Form)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_4.addWidget(self.close_button)
        self.execute_button = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.execute_button.sizePolicy().hasHeightForWidth())
        self.execute_button.setSizePolicy(sizePolicy)
        self.execute_button.setObjectName("execute_button")
        self.horizontalLayout_4.addWidget(self.execute_button)
        self.stop_button = QtGui.QPushButton(Form)
        self.stop_button.setFlat(False)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_4.addWidget(self.stop_button)
        self.gridLayout.addLayout(self.horizontalLayout_4, 7, 1, 1, 1)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 6, 0, 1, 2)

        self.retranslateUi(Form)
        self.controls_group.setCurrentIndex(0)
        QtCore.QObject.connect(self.scan_type, QtCore.SIGNAL("currentIndexChanged(int)"), Form.action_change_type)
        QtCore.QObject.connect(self.close_button, QtCore.SIGNAL("clicked()"), Form.close)
        QtCore.QObject.connect(self.execute_button, QtCore.SIGNAL("clicked()"), Form.action_execute_macro)
        QtCore.QObject.connect(self.stop_button, QtCore.SIGNAL("clicked()"), Form.action_stop_macro)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Scan type", None, QtGui.QApplication.UnicodeUTF8))
        self.scan_type.setItemText(0, QtGui.QApplication.translate("Form", "StartStopNp", None, QtGui.QApplication.UnicodeUTF8))
        self.scan_type.setItemText(1, QtGui.QApplication.translate("Form", "RangeNp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Start position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Stop position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "Np", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Np", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Motor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Integration time  ", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setText(QtGui.QApplication.translate("Form", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.execute_button.setText(QtGui.QApplication.translate("Form", "Execute macro", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_button.setText(QtGui.QApplication.translate("Form", "Stop macro", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.container import TaurusWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.TaurusWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

