# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/tmpSiBBbj.ui'
#
# Created: Wed Oct  2 14:28:51 2013
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1375, 714)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1260, 650))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.scan_widget_select = QtGui.QStackedWidget(Form)
        self.scan_widget_select.setObjectName("scan_widget_select")
        self.scan_graph_widget = QtGui.QWidget()
        self.scan_graph_widget.setObjectName("scan_graph_widget")
        self.gridLayout_5 = QtGui.QGridLayout(self.scan_graph_widget)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scan_plot_controls = QtGui.QWidget(self.scan_graph_widget)
        self.scan_plot_controls.setObjectName("scan_plot_controls")
        self.gridLayout_9 = QtGui.QGridLayout(self.scan_plot_controls)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setHorizontalSpacing(6)
        self.gridLayout_9.setVerticalSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scan_save_controls_widget = QtGui.QWidget(self.scan_plot_controls)
        self.scan_save_controls_widget.setObjectName("scan_save_controls_widget")
        self.scan_save_controls = QtGui.QHBoxLayout(self.scan_save_controls_widget)
        self.scan_save_controls.setSpacing(0)
        self.scan_save_controls.setMargin(0)
        self.scan_save_controls.setObjectName("scan_save_controls")
        self.button_scan_save_ascii = QtGui.QPushButton(self.scan_save_controls_widget)
        self.button_scan_save_ascii.setObjectName("button_scan_save_ascii")
        self.scan_save_controls.addWidget(self.button_scan_save_ascii)
        self.button_scan_save_image = QtGui.QPushButton(self.scan_save_controls_widget)
        self.button_scan_save_image.setObjectName("button_scan_save_image")
        self.scan_save_controls.addWidget(self.button_scan_save_image)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.scan_save_controls.addItem(spacerItem)
        self.horizontalLayout_6.addWidget(self.scan_save_controls_widget)
        self.scan_waiting_progress = QtGui.QProgressBar(self.scan_plot_controls)
        self.scan_waiting_progress.setMaximum(100)
        self.scan_waiting_progress.setProperty("value", 0)
        self.scan_waiting_progress.setObjectName("scan_waiting_progress")
        self.horizontalLayout_6.addWidget(self.scan_waiting_progress)
        self.scan_progressbar = QtGui.QProgressBar(self.scan_plot_controls)
        self.scan_progressbar.setProperty("value", 0)
        self.scan_progressbar.setObjectName("scan_progressbar")
        self.horizontalLayout_6.addWidget(self.scan_progressbar)
        self.button_new_scan = QtGui.QPushButton(self.scan_plot_controls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_new_scan.sizePolicy().hasHeightForWidth())
        self.button_new_scan.setSizePolicy(sizePolicy)
        self.button_new_scan.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_new_scan.setObjectName("button_new_scan")
        self.horizontalLayout_6.addWidget(self.button_new_scan)
        self.button_stop_scan = QtGui.QPushButton(self.scan_plot_controls)
        self.button_stop_scan.setObjectName("button_stop_scan")
        self.horizontalLayout_6.addWidget(self.button_stop_scan)
        self.gridLayout_9.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.stroboscope_controls = QtGui.QHBoxLayout()
        self.stroboscope_controls.setObjectName("stroboscope_controls")
        self.gridLayout_9.addLayout(self.stroboscope_controls, 0, 0, 1, 1)
        self.scan_plot_layout = QtGui.QGridLayout()
        self.scan_plot_layout.setSpacing(0)
        self.scan_plot_layout.setObjectName("scan_plot_layout")
        self.gridLayout_9.addLayout(self.scan_plot_layout, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.scan_plot_controls, 0, 0, 1, 1)
        self.scan_widget_select.addWidget(self.scan_graph_widget)
        self.scan_controls_widget = QtGui.QWidget()
        self.scan_controls_widget.setObjectName("scan_controls_widget")
        self.gridLayout_6 = QtGui.QGridLayout(self.scan_controls_widget)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scan_parameter_controls = QtGui.QWidget(self.scan_controls_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_parameter_controls.sizePolicy().hasHeightForWidth())
        self.scan_parameter_controls.setSizePolicy(sizePolicy)
        self.scan_parameter_controls.setMinimumSize(QtCore.QSize(750, 0))
        self.scan_parameter_controls.setMaximumSize(QtCore.QSize(750, 16777215))
        self.scan_parameter_controls.setObjectName("scan_parameter_controls")
        self.gridLayout_11 = QtGui.QGridLayout(self.scan_parameter_controls)
        self.gridLayout_11.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setHorizontalSpacing(0)
        self.gridLayout_11.setVerticalSpacing(5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.scan_controls = QtGui.QWidget(self.scan_parameter_controls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_controls.sizePolicy().hasHeightForWidth())
        self.scan_controls.setSizePolicy(sizePolicy)
        self.scan_controls.setMaximumSize(QtCore.QSize(16777215, 416))
        self.scan_controls.setObjectName("scan_controls")
        self.gridLayout_2 = QtGui.QGridLayout(self.scan_controls)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.scan_controls)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.select_scan_type = QtGui.QComboBox(self.scan_controls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_scan_type.sizePolicy().hasHeightForWidth())
        self.select_scan_type.setSizePolicy(sizePolicy)
        self.select_scan_type.setObjectName("select_scan_type")
        self.select_scan_type.addItem("")
        self.select_scan_type.addItem("")
        self.horizontalLayout.addWidget(self.select_scan_type)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.line = QtGui.QFrame(self.scan_controls)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 3)
        self.header_scan_settings = QtGui.QLabel(self.scan_controls)
        self.header_scan_settings.setStyleSheet("font-weight:bold;background:#f6b442;padding:5")
        self.header_scan_settings.setObjectName("header_scan_settings")
        self.gridLayout_2.addWidget(self.header_scan_settings, 2, 0, 1, 3)
        self.header_stroboscope_settings = QtGui.QLabel(self.scan_controls)
        self.header_stroboscope_settings.setStyleSheet("font-weight:bold;background:#f6b442;padding:5")
        self.header_stroboscope_settings.setObjectName("header_stroboscope_settings")
        self.gridLayout_2.addWidget(self.header_stroboscope_settings, 3, 0, 1, 3)
        self.groupBox = QtGui.QGroupBox(self.scan_controls)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    margin-top: 0.5em;\n"
" font-weight:bold\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
" font-weight:bold\n"
"   \n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.input_scan_summed = QtGui.QSpinBox(self.groupBox)
        self.input_scan_summed.setMinimum(1)
        self.input_scan_summed.setMaximum(99999)
        self.input_scan_summed.setObjectName("input_scan_summed")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.input_scan_summed)
        self.gridLayout_2.addWidget(self.groupBox, 4, 0, 1, 3)
        self.gridLayout_11.addWidget(self.scan_controls, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.scan_parameter_controls)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    margin-top: 0.5em;\n"
" font-weight:bold\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
" font-weight:bold\n"
"   \n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_18)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.input_scan_motor = QtGui.QLineEdit(self.groupBox_3)
        self.input_scan_motor.setEnabled(False)
        self.input_scan_motor.setObjectName("input_scan_motor")
        self.horizontalLayout_7.addWidget(self.input_scan_motor)
        self.input_scan_select_motor = QtGui.QToolButton(self.groupBox_3)
        self.input_scan_select_motor.setCursor(QtCore.Qt.PointingHandCursor)
        self.input_scan_select_motor.setObjectName("input_scan_select_motor")
        self.horizontalLayout_7.addWidget(self.input_scan_select_motor)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_motor_position = QtGui.QLabel(self.groupBox_3)
        self.label_motor_position.setObjectName("label_motor_position")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_motor_position)
        self.motor_position_controls = QtGui.QHBoxLayout()
        self.motor_position_controls.setObjectName("motor_position_controls")
        self.input_scan_start_position = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.input_scan_start_position.setDecimals(5)
        self.input_scan_start_position.setMinimum(-999999999.0)
        self.input_scan_start_position.setMaximum(999999999.0)
        self.input_scan_start_position.setObjectName("input_scan_start_position")
        self.motor_position_controls.addWidget(self.input_scan_start_position)
        self.input_scan_end_position = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.input_scan_end_position.setDecimals(5)
        self.input_scan_end_position.setMinimum(-999999999.0)
        self.input_scan_end_position.setMaximum(999999999.0)
        self.input_scan_end_position.setProperty("value", 0.0)
        self.input_scan_end_position.setObjectName("input_scan_end_position")
        self.motor_position_controls.addWidget(self.input_scan_end_position)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.motor_position_controls)
        self.label_step_size = QtGui.QLabel(self.groupBox_3)
        self.label_step_size.setObjectName("label_step_size")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_step_size)
        self.input_scan_motor_step = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.input_scan_motor_step.setDecimals(5)
        self.input_scan_motor_step.setProperty("value", 1.0)
        self.input_scan_motor_step.setObjectName("input_scan_motor_step")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.input_scan_motor_step)
        self.gridLayout_11.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.scanRegions = QtGui.QTableWidget(self.scan_parameter_controls)
        self.scanRegions.setColumnCount(6)
        self.scanRegions.setObjectName("scanRegions")
        self.scanRegions.setColumnCount(6)
        self.scanRegions.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.scanRegions.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.scanRegions.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.scanRegions.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.scanRegions.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.scanRegions.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.scanRegions.setHorizontalHeaderItem(5, item)
        self.scanRegions.verticalHeader().setDefaultSectionSize(30)
        self.gridLayout_11.addWidget(self.scanRegions, 2, 0, 1, 1)
        self.gridWidget = QtGui.QWidget(self.scan_parameter_controls)
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_12 = QtGui.QGridLayout(self.gridWidget)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.button_reset_selection = QtGui.QPushButton(self.gridWidget)
        self.button_reset_selection.setObjectName("button_reset_selection")
        self.horizontalLayout_15.addWidget(self.button_reset_selection)
        self.pushButton_2 = QtGui.QPushButton(self.gridWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_15.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.gridWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_15.addWidget(self.pushButton_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.button_scan_start = QtGui.QPushButton(self.gridWidget)
        self.button_scan_start.setObjectName("button_scan_start")
        self.horizontalLayout_15.addWidget(self.button_scan_start)
        self.gridLayout_12.addLayout(self.horizontalLayout_15, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.gridWidget, 3, 0, 1, 1)
        self.gridLayout_6.addWidget(self.scan_parameter_controls, 0, 0, 1, 1)
        self.detector_image = QtGui.QWidget(self.scan_controls_widget)
        self.detector_image.setObjectName("detector_image")
        self.gridLayout_13 = QtGui.QGridLayout(self.detector_image)
        self.gridLayout_13.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.detector_scan_image = QtGui.QGridLayout()
        self.detector_scan_image.setObjectName("detector_scan_image")
        self.gridLayout_13.addLayout(self.detector_scan_image, 0, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem2)
        self.button_refresh_detector_image = QtGui.QPushButton(self.detector_image)
        self.button_refresh_detector_image.setObjectName("button_refresh_detector_image")
        self.horizontalLayout_16.addWidget(self.button_refresh_detector_image)
        self.gridLayout_13.addLayout(self.horizontalLayout_16, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.detector_image, 0, 2, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.line_2 = QtGui.QFrame(self.scan_controls_widget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_19.addWidget(self.line_2)
        self.gridLayout_6.addLayout(self.horizontalLayout_19, 0, 1, 1, 1)
        self.scan_widget_select.addWidget(self.scan_controls_widget)
        self.gridLayout.addWidget(self.scan_widget_select, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.scan_widget_select.setCurrentIndex(1)
        QtCore.QObject.connect(self.button_stop_scan, QtCore.SIGNAL("clicked()"), Form.action_reset_scan)
        QtCore.QObject.connect(self.button_new_scan, QtCore.SIGNAL("clicked()"), Form.action_toggle_scan)
        QtCore.QObject.connect(self.button_scan_save_ascii, QtCore.SIGNAL("clicked()"), Form.action_save_scan_ascii)
        QtCore.QObject.connect(self.button_scan_save_image, QtCore.SIGNAL("clicked()"), Form.action_save_scan_image)
        QtCore.QObject.connect(Form, QtCore.SIGNAL("created()"), self.scan_waiting_progress.hide)
        QtCore.QObject.connect(Form, QtCore.SIGNAL("created()"), self.header_stroboscope_settings.hide)
        QtCore.QObject.connect(self.button_reset_selection, QtCore.SIGNAL("clicked()"), Form.action_reset_regions)
        QtCore.QObject.connect(self.select_scan_type, QtCore.SIGNAL("currentIndexChanged(int)"), Form.action_change_scan_type)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL("clicked()"), Form.action_load_regions)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL("clicked()"), Form.action_save_regions)
        QtCore.QObject.connect(self.button_scan_start, QtCore.SIGNAL("clicked()"), Form.action_start_scan)
        QtCore.QObject.connect(self.button_refresh_detector_image, QtCore.SIGNAL("clicked()"), Form.action_refresh_detector_image)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.button_scan_save_ascii.setText(QtGui.QApplication.translate("Form", "Save as ascii", None, QtGui.QApplication.UnicodeUTF8))
        self.button_scan_save_image.setText(QtGui.QApplication.translate("Form", "Save as image", None, QtGui.QApplication.UnicodeUTF8))
        self.scan_waiting_progress.setFormat(QtGui.QApplication.translate("Form", "Waiting progress: %p%", None, QtGui.QApplication.UnicodeUTF8))
        self.scan_progressbar.setFormat(QtGui.QApplication.translate("Form", "Scan progress: %p%", None, QtGui.QApplication.UnicodeUTF8))
        self.button_new_scan.setText(QtGui.QApplication.translate("Form", "Repeat scan", None, QtGui.QApplication.UnicodeUTF8))
        self.button_stop_scan.setText(QtGui.QApplication.translate("Form", "Stop scan", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Scan type", None, QtGui.QApplication.UnicodeUTF8))
        self.select_scan_type.setItemText(0, QtGui.QApplication.translate("Form", "Basic scan", None, QtGui.QApplication.UnicodeUTF8))
        self.select_scan_type.setItemText(1, QtGui.QApplication.translate("Form", "Stroboscope", None, QtGui.QApplication.UnicodeUTF8))
        self.header_scan_settings.setText(QtGui.QApplication.translate("Form", "Basic scan settings", None, QtGui.QApplication.UnicodeUTF8))
        self.header_stroboscope_settings.setText(QtGui.QApplication.translate("Form", "Stroboscope scan settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Detector settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Summed", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Motor settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Motor", None, QtGui.QApplication.UnicodeUTF8))
        self.input_scan_select_motor.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_motor_position.setText(QtGui.QApplication.translate("Form", "Motor position (from, to)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_step_size.setText(QtGui.QApplication.translate("Form", "Step size", None, QtGui.QApplication.UnicodeUTF8))
        self.scanRegions.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.scanRegions.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "x0", None, QtGui.QApplication.UnicodeUTF8))
        self.scanRegions.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "y0", None, QtGui.QApplication.UnicodeUTF8))
        self.scanRegions.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "x1", None, QtGui.QApplication.UnicodeUTF8))
        self.scanRegions.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "y1", None, QtGui.QApplication.UnicodeUTF8))
        self.scanRegions.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "Action", None, QtGui.QApplication.UnicodeUTF8))
        self.button_reset_selection.setText(QtGui.QApplication.translate("Form", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Form", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.button_scan_start.setText(QtGui.QApplication.translate("Form", "Start scan", None, QtGui.QApplication.UnicodeUTF8))
        self.button_refresh_detector_image.setText(QtGui.QApplication.translate("Form", "Refresh image from detector", None, QtGui.QApplication.UnicodeUTF8))

