# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/tmpE2tyB5.ui'
#
# Created: Wed Jan 22 19:14:32 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(533, 504)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_select = QtGui.QStackedWidget(Form)
        self.widget_select.setObjectName("widget_select")
        self.motor_widget = QtGui.QWidget()
        self.motor_widget.setObjectName("motor_widget")
        self.gridLayout_2 = QtGui.QGridLayout(self.motor_widget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.macro_controls_loop = QtGui.QWidget(self.motor_widget)
        self.macro_controls_loop.setEnabled(True)
        self.macro_controls_loop.setStyleSheet("b")
        self.macro_controls_loop.setObjectName("macro_controls_loop")
        self.loop_macro_controls = QtGui.QGridLayout(self.macro_controls_loop)
        self.loop_macro_controls.setMargin(0)
        self.loop_macro_controls.setHorizontalSpacing(0)
        self.loop_macro_controls.setObjectName("loop_macro_controls")
        self.label_27 = QtGui.QLabel(self.macro_controls_loop)
        self.label_27.setStyleSheet("font-weight:bold;background:#f6b442;padding:5")
        self.label_27.setObjectName("label_27")
        self.loop_macro_controls.addWidget(self.label_27, 0, 0, 1, 2)
        self.label_28 = QtGui.QLabel(self.macro_controls_loop)
        self.label_28.setStyleSheet("font-weight:bold;background:#f6b442;padding:5")
        self.label_28.setObjectName("label_28")
        self.loop_macro_controls.addWidget(self.label_28, 2, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(self.macro_controls_loop)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    margin-top: 0.5em;\n"
" font-weight:bold\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
" font-weight:bold\n"
"   \n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 0, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.macro_input_motor_loop = QtGui.QLineEdit(self.groupBox_3)
        self.macro_input_motor_loop.setEnabled(False)
        self.macro_input_motor_loop.setObjectName("macro_input_motor_loop")
        self.horizontalLayout_21.addWidget(self.macro_input_motor_loop)
        self.macro_button_select_motor_loop = QtGui.QToolButton(self.groupBox_3)
        self.macro_button_select_motor_loop.setCursor(QtCore.Qt.PointingHandCursor)
        self.macro_button_select_motor_loop.setObjectName("macro_button_select_motor_loop")
        self.horizontalLayout_21.addWidget(self.macro_button_select_motor_loop)
        self.gridLayout_5.addLayout(self.horizontalLayout_21, 0, 1, 1, 1)
        self.macro_loop_step = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.macro_loop_step.setDecimals(5)
        self.macro_loop_step.setMaximum(99999.0)
        self.macro_loop_step.setObjectName("macro_loop_step")
        self.gridLayout_5.addWidget(self.macro_loop_step, 2, 1, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.macro_loop_start = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.macro_loop_start.setDecimals(5)
        self.macro_loop_start.setMinimum(-99999.0)
        self.macro_loop_start.setMaximum(99999.0)
        self.macro_loop_start.setObjectName("macro_loop_start")
        self.horizontalLayout_20.addWidget(self.macro_loop_start)
        self.macro_loop_end = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.macro_loop_end.setDecimals(5)
        self.macro_loop_end.setMinimum(-99999.0)
        self.macro_loop_end.setMaximum(99999.0)
        self.macro_loop_end.setProperty("value", 0.0)
        self.macro_loop_end.setObjectName("macro_loop_end")
        self.horizontalLayout_20.addWidget(self.macro_loop_end)
        self.gridLayout_5.addLayout(self.horizontalLayout_20, 1, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 2, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 0, 0, 1, 1)
        self.loop_macro_controls.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.macro_controls_loop, 0, 0, 1, 1)
        self.table_macro = QtGui.QTableWidget(self.motor_widget)
        self.table_macro.setEnabled(True)
        self.table_macro.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.table_macro.setShowGrid(True)
        self.table_macro.setGridStyle(QtCore.Qt.SolidLine)
        self.table_macro.setObjectName("table_macro")
        self.table_macro.setColumnCount(10)
        self.table_macro.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_macro.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_macro.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_macro.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_macro.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_macro.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_macro.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table_macro.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table_macro.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.table_macro.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.table_macro.setHorizontalHeaderItem(9, item)
        self.table_macro.horizontalHeader().setCascadingSectionResizes(True)
        self.table_macro.horizontalHeader().setStretchLastSection(True)
        self.table_macro.verticalHeader().setCascadingSectionResizes(True)
        self.table_macro.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.table_macro, 2, 0, 1, 1)
        self.widget_select.addWidget(self.motor_widget)
        self.time_widget = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_widget.sizePolicy().hasHeightForWidth())
        self.time_widget.setSizePolicy(sizePolicy)
        self.time_widget.setMaximumSize(QtCore.QSize(16777215, 16777213))
        self.time_widget.setObjectName("time_widget")
        self.gridLayout_3 = QtGui.QGridLayout(self.time_widget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(self.time_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    margin-top: 0.5em;\n"
" font-weight:bold\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
" font-weight:bold\n"
"   \n"
"}")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.macro_input_sampleName = QtGui.QLineEdit(self.groupBox)
        self.macro_input_sampleName.setObjectName("macro_input_sampleName")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.macro_input_sampleName)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.macro_input_filesafter = QtGui.QSpinBox(self.groupBox)
        self.macro_input_filesafter.setMaximum(999999999)
        self.macro_input_filesafter.setProperty("value", 1)
        self.macro_input_filesafter.setObjectName("macro_input_filesafter")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.macro_input_filesafter)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.macro_input_summed = QtGui.QSpinBox(self.groupBox)
        self.macro_input_summed.setMinimum(1)
        self.macro_input_summed.setMaximum(999999999)
        self.macro_input_summed.setObjectName("macro_input_summed")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.macro_input_summed)
        self.macro_input_comment = QtGui.QLineEdit(self.groupBox)
        self.macro_input_comment.setMaxLength(900)
        self.macro_input_comment.setObjectName("macro_input_comment")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.macro_input_comment)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.time_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    margin-top: 0.5em;\n"
" font-weight:bold\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
" font-weight:bold\n"
"   \n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.macro_wait_time = QtGui.QSpinBox(self.groupBox_2)
        self.macro_wait_time.setMaximum(999999999)
        self.macro_wait_time.setProperty("value", 1)
        self.macro_wait_time.setObjectName("macro_wait_time")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.macro_wait_time)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.macro_input_repeat = QtGui.QSpinBox(self.groupBox_2)
        self.macro_input_repeat.setMinimum(1)
        self.macro_input_repeat.setMaximum(999999999)
        self.macro_input_repeat.setProperty("value", 1)
        self.macro_input_repeat.setObjectName("macro_input_repeat")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.macro_input_repeat)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_take_dark = QtGui.QCheckBox(self.groupBox_2)
        self.check_take_dark.setObjectName("check_take_dark")
        self.horizontalLayout.addWidget(self.check_take_dark)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout_3.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.macro_reset_fileindex = QtGui.QCheckBox(self.groupBox_2)
        self.macro_reset_fileindex.setChecked(True)
        self.macro_reset_fileindex.setObjectName("macro_reset_fileindex")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.macro_reset_fileindex)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.widget_select.addWidget(self.time_widget)
        self.temperature_widget = QtGui.QWidget()
        self.temperature_widget.setObjectName("temperature_widget")
        self.gridLayout_7 = QtGui.QGridLayout(self.temperature_widget)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.table_temperature_macro = QtGui.QTableWidget(self.temperature_widget)
        self.table_temperature_macro.setEnabled(True)
        self.table_temperature_macro.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.table_temperature_macro.setShowGrid(True)
        self.table_temperature_macro.setGridStyle(QtCore.Qt.SolidLine)
        self.table_temperature_macro.setObjectName("table_temperature_macro")
        self.table_temperature_macro.setColumnCount(10)
        self.table_temperature_macro.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_temperature_macro.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_temperature_macro.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_temperature_macro.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_temperature_macro.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_temperature_macro.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_temperature_macro.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table_temperature_macro.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table_temperature_macro.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.table_temperature_macro.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.table_temperature_macro.setHorizontalHeaderItem(9, item)
        self.table_temperature_macro.horizontalHeader().setCascadingSectionResizes(True)
        self.table_temperature_macro.horizontalHeader().setStretchLastSection(True)
        self.table_temperature_macro.verticalHeader().setCascadingSectionResizes(True)
        self.table_temperature_macro.verticalHeader().setStretchLastSection(False)
        self.gridLayout_7.addWidget(self.table_temperature_macro, 0, 0, 1, 1)
        self.widget_select.addWidget(self.temperature_widget)
        self.gridLayout.addWidget(self.widget_select, 1, 0, 1, 1)
        self.macro_main_controls = QtGui.QWidget(Form)
        self.macro_main_controls.setObjectName("macro_main_controls")
        self.gridLayout_4 = QtGui.QGridLayout(self.macro_main_controls)
        self.gridLayout_4.setContentsMargins(0, 5, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(5)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.button_save_macro = QtGui.QPushButton(self.macro_main_controls)
        self.button_save_macro.setObjectName("button_save_macro")
        self.gridLayout_4.addWidget(self.button_save_macro, 0, 1, 1, 1)
        self.button_load_macro = QtGui.QPushButton(self.macro_main_controls)
        self.button_load_macro.setObjectName("button_load_macro")
        self.gridLayout_4.addWidget(self.button_load_macro, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(255, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 3, 1, 1)
        self.button_run_macros = QtGui.QPushButton(self.macro_main_controls)
        self.button_run_macros.setStyleSheet("QPushButton{background:#80FF9F}\n"
"QPushButton:disabled{ background:silver;color:grey }")
        self.button_run_macros.setObjectName("button_run_macros")
        self.gridLayout_4.addWidget(self.button_run_macros, 0, 4, 1, 1)
        self.button_macro_reset = QtGui.QPushButton(self.macro_main_controls)
        self.button_macro_reset.setObjectName("button_macro_reset")
        self.gridLayout_4.addWidget(self.button_macro_reset, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.macro_main_controls, 2, 0, 1, 1)
        self.macro_wait_controls = QtGui.QGroupBox(Form)
        self.macro_wait_controls.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    margin-top: 0.5em;\n"
" font-weight:bold\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
" font-weight:bold\n"
"   \n"
"}")
        self.macro_wait_controls.setObjectName("macro_wait_controls")
        self.gridLayout_9 = QtGui.QGridLayout(self.macro_wait_controls)
        self.gridLayout_9.setSpacing(5)
        self.gridLayout_9.setContentsMargins(5, 10, 5, 5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.macro_waiting_progressbar = QtGui.QProgressBar(self.macro_wait_controls)
        self.macro_waiting_progressbar.setProperty("value", 0)
        self.macro_waiting_progressbar.setObjectName("macro_waiting_progressbar")
        self.gridLayout_9.addWidget(self.macro_waiting_progressbar, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.macro_wait_controls, 3, 0, 1, 1)
        self.macro_steps_controls = QtGui.QGroupBox(Form)
        self.macro_steps_controls.setEnabled(True)
        self.macro_steps_controls.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    margin-top: 0.5em;\n"
" font-weight:bold\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
" font-weight:bold\n"
"   \n"
"}")
        self.macro_steps_controls.setObjectName("macro_steps_controls")
        self.gridLayout_6 = QtGui.QGridLayout(self.macro_steps_controls)
        self.gridLayout_6.setSpacing(5)
        self.gridLayout_6.setContentsMargins(5, 10, 5, 5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.current_operation_status = QtGui.QLabel(self.macro_steps_controls)
        self.current_operation_status.setStyleSheet("background:orange;padding:5")
        self.current_operation_status.setObjectName("current_operation_status")
        self.gridLayout_6.addWidget(self.current_operation_status, 0, 0, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.macro_progressbar = QtGui.QProgressBar(self.macro_steps_controls)
        self.macro_progressbar.setProperty("value", 0)
        self.macro_progressbar.setObjectName("macro_progressbar")
        self.horizontalLayout_3.addWidget(self.macro_progressbar)
        self.input_macro_halt = QtGui.QPushButton(self.macro_steps_controls)
        self.input_macro_halt.setStyleSheet("QPushButton{background:purple;font-weight:bold;color:#fff;}\n"
"QPushButton:disabled{ background:silver;color:grey }")
        self.input_macro_halt.setObjectName("input_macro_halt")
        self.horizontalLayout_3.addWidget(self.input_macro_halt)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.macro_steps_controls, 4, 0, 1, 1)
        self.label_23.setBuddy(self.macro_loop_start)
        self.label_26.setBuddy(self.macro_loop_step)
        self.label_22.setBuddy(self.macro_button_select_motor_loop)

        self.retranslateUi(Form)
        self.widget_select.setCurrentIndex(1)
        QtCore.QObject.connect(self.table_macro, QtCore.SIGNAL("itemChanged(QTableWidgetItem*)"), Form.action_macro_edited)
        QtCore.QObject.connect(Form, QtCore.SIGNAL("created()"), self.macro_controls_loop.hide)
        QtCore.QObject.connect(self.button_macro_reset, QtCore.SIGNAL("clicked()"), Form.action_reset_macro)
        QtCore.QObject.connect(self.button_save_macro, QtCore.SIGNAL("clicked()"), Form.action_save_macro)
        QtCore.QObject.connect(self.button_load_macro, QtCore.SIGNAL("clicked()"), Form.action_load_macro)
        QtCore.QObject.connect(self.button_run_macros, QtCore.SIGNAL("clicked()"), Form.action_start_macro)
        QtCore.QObject.connect(Form, QtCore.SIGNAL("created()"), self.macro_steps_controls.hide)
        QtCore.QObject.connect(Form, QtCore.SIGNAL("created()"), self.macro_wait_controls.hide)
        QtCore.QObject.connect(self.input_macro_halt, QtCore.SIGNAL("clicked()"), Form.action_halt_macro)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Macro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Form", "Outer loop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Form", "Inner loop", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Loop motor settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Form", "Motor position (from, to)", None, QtGui.QApplication.UnicodeUTF8))
        self.macro_button_select_motor_loop.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.macro_loop_step.setToolTip(QtGui.QApplication.translate("Form", "Specify step size", None, QtGui.QApplication.UnicodeUTF8))
        self.macro_loop_start.setToolTip(QtGui.QApplication.translate("Form", "Specify motor start position", None, QtGui.QApplication.UnicodeUTF8))
        self.macro_loop_end.setToolTip(QtGui.QApplication.translate("Form", "Specify motor end position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Form", "Step size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Form", "Looping motor", None, QtGui.QApplication.UnicodeUTF8))
        self.table_macro.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Sample name", None, QtGui.QApplication.UnicodeUTF8))
        self.table_macro.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Motor", None, QtGui.QApplication.UnicodeUTF8))
        self.table_macro.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "Motor device", None, QtGui.QApplication.UnicodeUTF8))
        self.table_macro.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.table_macro.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "Summed", None, QtGui.QApplication.UnicodeUTF8))
        self.table_macro.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "Post trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.table_macro.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "Wait (sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.table_macro.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Form", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.table_macro.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("Form", "Dark", None, QtGui.QApplication.UnicodeUTF8))
        self.table_macro.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("Form", "Action", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Detector settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Sample name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Summed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Post trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "User comment", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Macro settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Wait after shot (sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Number of iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.check_take_dark.setText(QtGui.QApplication.translate("Form", "Take dark before macro step", None, QtGui.QApplication.UnicodeUTF8))
        self.macro_reset_fileindex.setText(QtGui.QApplication.translate("Form", "Reset detector fileindex", None, QtGui.QApplication.UnicodeUTF8))
        self.table_temperature_macro.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Sample name", None, QtGui.QApplication.UnicodeUTF8))
        self.table_temperature_macro.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Hotblower", None, QtGui.QApplication.UnicodeUTF8))
        self.table_temperature_macro.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "Hotblower device", None, QtGui.QApplication.UnicodeUTF8))
        self.table_temperature_macro.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.table_temperature_macro.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "Summed", None, QtGui.QApplication.UnicodeUTF8))
        self.table_temperature_macro.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "Post trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.table_temperature_macro.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "Wait (sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.table_temperature_macro.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Form", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.table_temperature_macro.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("Form", "Dark", None, QtGui.QApplication.UnicodeUTF8))
        self.table_temperature_macro.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("Form", "Action", None, QtGui.QApplication.UnicodeUTF8))
        self.button_save_macro.setText(QtGui.QApplication.translate("Form", "Save macro", None, QtGui.QApplication.UnicodeUTF8))
        self.button_load_macro.setText(QtGui.QApplication.translate("Form", "Load macro", None, QtGui.QApplication.UnicodeUTF8))
        self.button_run_macros.setText(QtGui.QApplication.translate("Form", "Start macro", None, QtGui.QApplication.UnicodeUTF8))
        self.button_macro_reset.setText(QtGui.QApplication.translate("Form", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.macro_wait_controls.setTitle(QtGui.QApplication.translate("Form", "Waiting", None, QtGui.QApplication.UnicodeUTF8))
        self.macro_waiting_progressbar.setFormat(QtGui.QApplication.translate("Form", "Waiting progress: %p%", None, QtGui.QApplication.UnicodeUTF8))
        self.macro_steps_controls.setTitle(QtGui.QApplication.translate("Form", "Macro progress and status", None, QtGui.QApplication.UnicodeUTF8))
        self.macro_progressbar.setFormat(QtGui.QApplication.translate("Form", "Macro progress: %p%", None, QtGui.QApplication.UnicodeUTF8))
        self.input_macro_halt.setText(QtGui.QApplication.translate("Form", "Stop macro", None, QtGui.QApplication.UnicodeUTF8))

