# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/tmpK3Y7Hy.ui'
#
# Created: Mon Jun 16 17:33:47 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(467, 274)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.formLayout_3 = QtGui.QFormLayout(self.page_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(0, 0, 0, -1)
        self.formLayout_3.setHorizontalSpacing(10)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_8 = QtGui.QLabel(self.page_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.macro_value_from = QtGui.QDoubleSpinBox(self.page_3)
        self.macro_value_from.setDecimals(5)
        self.macro_value_from.setMinimum(-99999.0)
        self.macro_value_from.setMaximum(99999.0)
        self.macro_value_from.setObjectName("macro_value_from")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.macro_value_from)
        self.label_9 = QtGui.QLabel(self.page_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.macro_value_to = QtGui.QDoubleSpinBox(self.page_3)
        self.macro_value_to.setDecimals(5)
        self.macro_value_to.setMinimum(-99999.0)
        self.macro_value_to.setMaximum(99999.0)
        self.macro_value_to.setObjectName("macro_value_to")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.macro_value_to)
        self.label_10 = QtGui.QLabel(self.page_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.macro_steps = QtGui.QSpinBox(self.page_3)
        self.macro_steps.setMinimum(1)
        self.macro_steps.setMaximum(9999999)
        self.macro_steps.setObjectName("macro_steps")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.macro_steps)
        self.label_11 = QtGui.QLabel(self.page_3)
        self.label_11.setStyleSheet("m")
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_11)
        self.macro_integration_time = QtGui.QDoubleSpinBox(self.page_3)
        self.macro_integration_time.setDecimals(5)
        self.macro_integration_time.setMinimum(0.0)
        self.macro_integration_time.setMaximum(99999.0)
        self.macro_integration_time.setObjectName("macro_integration_time")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.macro_integration_time)
        self.label_7 = QtGui.QLabel(self.page_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_motor_name = QtGui.QLabel(self.page_3)
        self.label_motor_name.setObjectName("label_motor_name")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_motor_name)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget, 2, 0, 1, 2)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 2)
        self.pushButton_3 = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_4 = QtGui.QPushButton(Dialog)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL("clicked()"), Dialog.close)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL("clicked()"), self.macro_integration_time.clear)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL("clicked()"), self.macro_steps.clear)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL("clicked()"), self.macro_value_to.clear)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL("clicked()"), self.macro_value_from.clear)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL("clicked()"), Dialog.action_execute_macro)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Sardana motor macro executor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Macro type", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "Ascan", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Start position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Final position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Number of steps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Integration time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Motor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_motor_name.setText(QtGui.QApplication.translate("Dialog", "motor name", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Dialog", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("Dialog", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("Dialog", "Execute macro", None, QtGui.QApplication.UnicodeUTF8))

